title: My Journey into the World of Coding and Vanlife
author: KSylv88
email: address@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Trying to make a sustainable future while living life on the road by learning to code!

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
